# ストレージ空き容量が最小値（free-space）を下回った場合に自動でGCを実行する
min-free = 10000000000 # 10GB未満になったら自動削除を開始

# GC実行時に確保する最大空き容量
max-free = 30000000000 # 30GB空くまで削除を継続

# 構築中のディスク満杯を防ぐ
keep-outputs = false
keep-derivations = false

experimental-features = nix-command flakes
