min-free = 10000000000
max-free = 30000000000

keep-outputs = false
keep-derivations = false
auto-optimise-store = true

eval-cache = true

max-jobs = auto
cores = 0
http2 = true
max-substitution-jobs = 128

experimental-features = nix-command flakes
