# 1. 壁紙のプリロード (必須)
# ファイルパスを絶対パスまたはホームディレクトリからの相対パスで指定します。
# preload = /home/toyama/OneDrive/画像/壁紙/WIP Dark.png
# preload = /home/toyama/Pictures/wallpaper/my_arch_bg_2.jpg 

# 2. 壁紙の適用
# 形式: wallpaper = <モニター名>, <ファイルパス>
# 確認したモニター名（例: DP-1）と壁紙のパスを指定します。
# wallpaper = eDP-1, /home/toyama/OneDrive/画像/壁紙/WIP Dark.png
wallpaper {
    monitor = eDP-1
    path = /home/toyama/OneDrive/画像/壁紙/john-rodenn-castillo-rQqWOHZ96OM-unsplash.jpg
    fit_mode = cover
}

# 複数のモニターがある場合は、モニターごとに設定します。
# wallpaper = HDMI-A-1, ~/Pictures/wallpaper/second_screen.png
wallpaper {
    monitor = HDMI-A-1
    path = /home/toyama/OneDrive/画像/壁紙/WIP Dark.png
    fit_mode = cover
}

# 3. スケーリングモード (オプション)
# 壁紙がモニターのサイズに合わない場合の表示方法を設定します。
# 選択肢: fill (全体を埋める, 推奨), fit, stretch, center, tile
ipc = on # IPC通信を有効化（外部からの壁紙変更を可能にする）
