modmap:
  - name: Global
    remap:
      CTRL_R: KEY_PRINT
      ALT_R: KEY_ESC
      CapsLock: KEY_ZENKAKUHANKAKU
      KEY_SPACE: 
        held: Shift_L
        alone: KEY_SPACE
        alone_timeout_millis: 100
        # hold_threshold_millis: 100
        free_hold: true
    window:
      not: [/Minecraft.*/]
